services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      VITE_API_BASE_URL: http://your-backend-domain.com/api
    restart: unless-stopped
